title: Defending an unpopular opinion on React
short: Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
date: 2024-07-19
tags:
  - Opinion
  - Web
  - React
